package main.enums;

public enum PromptMessage {
    BIOME_MENU,
    CUSTOM_DIFF_MENU,
    DIFF_MENU,
    MAIN_MENU,
    RACE_MENU,
    TURN_MENU,
    PRIORITY_MENU,
    END_PHASE,
    RESOURCE_VIEW,
    BLURB,
    INVENTORY_VIEW,
    VILLAGERS,
    POP_SETUP,
    BOARD_SIZE,
    NEW_GAME_HUB,
    GAME_BOARD,
    LOGIN,
    START_ERA,
    BUILDINGS,
    ARCHIVE,
    STAT_VIEW,
    MERCHANT,
    TRAINING,
    SALE_MERCHANT,
    DEV_CONSOLE
}
